<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGMhnSq4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGMhnSq4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGMhnSq4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGMhnSq4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGMhnSq4\App_KernelDevDebugContainer([
    'container.build_hash' => 'GMhnSq4',
    'container.build_id' => 'a81063f7',
    'container.build_time' => 1642111648,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGMhnSq4');
