<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNtsArn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNtsArn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNtsArn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNtsArn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNNtsArn\App_KernelDevDebugContainer([
    'container.build_hash' => 'NNtsArn',
    'container.build_id' => 'b0062508',
    'container.build_time' => 1642090568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNtsArn');
